"""Add QA Checklist tables and version columns

Revision ID: 5f59b919b761
Revises: 0003
Create Date: 2026-10-04 20:46:44.175975

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5f59b919b761'
down_revision: str | Sequence[str] | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qa_checklist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('qa_checklist_version',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('checklist_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('activated_by', sa.String(length=64), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['checklist_id'], ['qa_checklist.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checklist_id', 'version_number', name='uq_qa_checklist_version_number')
    )
    with op.batch_alter_table('qa_checklist_version', schema=None) as batch_op:
        batch_op.create_index('ix_qa_checklist_version_active', ['checklist_id', 'status'], unique=True, postgresql_where=sa.text("status = 'active'"), sqlite_where=sa.text("status = 'active'"))
        batch_op.create_index('ix_qa_checklist_version_status', ['status'], unique=False)

    op.create_table('qa_checklist_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('item_key', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('critical', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('evaluation_type', sa.String(length=32), nullable=False),
    sa.Column('policy_reference', sa.Text(), nullable=True),
    sa.Column('applicability_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['qa_checklist_version.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'item_key', name='uq_qa_checklist_item_key')
    )
    # Unrelated tables removed from migration

    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checklist_version_id', sa.Integer(), nullable=True))

    # Unrelated tables removed from migration

    with op.batch_alter_table('qa_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checklist_version_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qa_results', schema=None) as batch_op:
        batch_op.drop_column('checklist_version_id')

    # Unrelated tables removed from migration

    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_column('checklist_version_id')

    # Unrelated tables removed from migration
    op.drop_table('qa_checklist_item')
    with op.batch_alter_table('qa_checklist_version', schema=None) as batch_op:
        batch_op.drop_index('ix_qa_checklist_version_status')
        batch_op.drop_index('ix_qa_checklist_version_active', postgresql_where=sa.text("status = 'active'"), sqlite_where=sa.text("status = 'active'"))

    op.drop_table('qa_checklist_version')
    op.drop_table('qa_checklist')
    # ### end Alembic commands ###
